/*******************************************************/
/*      This file is automatically generated           */
/*        !!! DO NOT MODIFY THIS FILE !!!              */
/*        All changes will be overwritten              */
/*******************************************************/

#ifndef _OBJTAB_H_
#define _OBJTAB_H_

// Object ID list
#define CNT_CONTAINER0 0 // CONTAINER0
#define CNT_CONTAINER1 1 // CONTAINER1
#define MSK_MASKE0 0 // MASKE0
#define OBJ_PIPEFLOW6 6 // PIPEFLOW6
#define OBJ_PIPEFLOW9 9 // PIPEFLOW9
#define OBJ_TRUETYPEMENUTEXT0 19 // TRUETYPEMENUTEXT0
#define OBJ_TRUETYPEMENUTEXT1 20 // TRUETYPEMENUTEXT1
#define OBJ_TRUETYPEMENUTEXT14 15 // TRUETYPEMENUTEXT14
#define OBJ_TRUETYPEMENUTEXT16 16 // TRUETYPEMENUTEXT16
#define OBJ_TRUETYPEMENUTEXT17 17 // TRUETYPEMENUTEXT17
#define OBJ_TRUETYPEMENUTEXT18 18 // TRUETYPEMENUTEXT18
#define OBJ_TRUETYPEMENUTEXT2 21 // TRUETYPEMENUTEXT2
#define OBJ_TRUETYPEMENUTEXT3 22 // TRUETYPEMENUTEXT3
#define OBJ_TRUETYPETEXT5 5 // TRUETYPETEXT5

// Attribute list
#define ATTR_INVERTED                0x00000001		// Attribute inverted
#define ATTR_BLINKING                0x00000002		// Attribute blinking
#define ATTR_UNDERLINED              0x00000004		// Attribute underlined
#define ATTR_VISIBLE                 0x00000008		// Attribute visible
#define ATTR_TRANSPARENT             0x00000010		// Attribute transparent
#define ATTR_SMOOTH                  0x00000020		// Attribute smooth
#define ATTR_NOMINAL                 0x00000100		// Attribute nominal
#define ATTR_LOWER_BLINK_FG          0x00000200		// Attribute lower foreground blink
#define ATTR_UPPER_BLINK_FG          0x00000400		// Attribute upper foreground blink
#define ATTR_LOWER_BLINK_BK          0x00000800		// Attribute lower background blink
#define ATTR_UPPER_BLINK_BK          0x00001000		// Attribute upper background blink
#define ATTR_GRAB_FOCUS              0x00002000		// Attribute grab focus
#define ATTR_UPDATE_ON_EDIT          0x00004000		// Attribute update on edit
#define ATTR_ANIMATED                0x00008000		// Attribute animated
#define ATTR_ALIGN_CENTER            0x00010000		// Attribute align center
#define ATTR_ALIGN_RIGHT_BOTTOM      0x00020000		// Attribute align right bottom
#define ATTR_TEXTFLOW_RIGHT_TO_LEFT  0x00040000		// Attribute drawmode right to left
#define ATTR_TEXTFLOW_TOP_TO_BOTTOM  0x00080000		// Attribute drawmode top to bottom

#if (__GNUC__ > 4)
#define DRAWMODE_DEPRECATED(x)  __attribute__ ((deprecated(x)))
#else
#define DRAWMODE_DEPRECATED(x)  __attribute__ ((deprecated))
#endif

static const uint32_t ATTR_DRAWMODE_TOP_TO_BOTTOM DRAWMODE_DEPRECATED("Use ATTR_TEXTFLOW_RIGHT_TO_LEFT") = 0x00040000;
static const uint32_t ATTR_DRAWMODE_RIGHT_TO_LEFT DRAWMODE_DEPRECATED("Use ATTR_TEXTFLOW_TOP_TO_BOTTOM") = 0x00080000;
#endif
