#-----------------------------------------------
# srclist.mk
# This file is automatically generated, don't try to edit it
# all modifications will be lost with next build
#-----------------------------------------------
ARCH := armv7
TARGET = A07C-buttonList
BASEBOARD := G440
# Listing C/C++ source files here. (C dependencies are automatically generated.)
SRC += .\cgen\__GS_driverapi.c 
SRC += .\cgen\MCQ_dev.c 
SRC += .\cgen\RCColor.c 
SRC += .\cgen\RCText.c 
SRC += .\cgen\gdsPrjUserCInfo_CM.c 
SRC += .\cgen\gdsPrjUserCInfo_VR.c 
SRC += A07C-buttonList.c 
# Debug options
FLAG_DEBUG = 0
FLAG_WINSIMU = 1
# Listing additional object files here.
ADDOBJ = 
LIBS = CanOpenSlaveStack-DSeriesS fpgaS iniS logS mbedcrypto mbedtls mbedx509 gsNetwork-sslS openSYDE-serverS UserCAPIS gsUtilS 
LIBDIRS = 
