/*******************************************************/
/*      This file is automatically generated           */
/*        !!! DO NOT MODIFY THIS FILE !!!              */
/*        All changes will be overwritten              */
/*******************************************************/

#ifndef _VARTAB_H_
#define _VARTAB_H_

/* Variable Table */
#define HDL_STROEMUNG 1               // Handle of STROEMUNG
#define IDX_STROEMUNG 0               // Index
#define HDL_SYS_U_SUPPLY 65524        // Handle of SYS_U_SUPPLY
#define IDX_SYS_U_SUPPLY 1            // Index
#define HDL_SYS_ENC_RIGHT 65525       // Handle of SYS_ENC_RIGHT
#define IDX_SYS_ENC_RIGHT 2           // Index
#define HDL_SYS_ENC_LEFT 65526        // Handle of SYS_ENC_LEFT
#define IDX_SYS_ENC_LEFT 3            // Index
#define HDL_SYS_TEMPERATURE 65527     // Handle of SYS_TEMPERATURE
#define IDX_SYS_TEMPERATURE 4         // Index
#define HDL_SYS_PRIORITY 65528        // Handle of SYS_PRIORITY
#define IDX_SYS_PRIORITY 5            // Index
#define HDL_SYS_COLOR 65529           // Handle of SYS_COLOR
#define IDX_SYS_COLOR 6               // Index
#define HDL_SYS_LANGUAGE 65530        // Handle of SYS_LANGUAGE
#define IDX_SYS_LANGUAGE 7            // Index
#define HDL_SYS_OPERATING_TIME 65531  // Handle of SYS_OPERATING_TIME
#define IDX_SYS_OPERATING_TIME 8      // Index

/* Variable Groups */

/* Variable Table (old style) */
#ifdef USE_OLDSTYLE_VARIABLE_SYMBOLS
#define STROEMUNG 1               // Handle of STROEMUNG
#define STROEMUNG_idx 0           // Index
#define SYS_U_SUPPLY 65524        // Handle of SYS_U_SUPPLY
#define SYS_U_SUPPLY_idx 1        // Index
#define SYS_ENC_RIGHT 65525       // Handle of SYS_ENC_RIGHT
#define SYS_ENC_RIGHT_idx 2       // Index
#define SYS_ENC_LEFT 65526        // Handle of SYS_ENC_LEFT
#define SYS_ENC_LEFT_idx 3        // Index
#define SYS_TEMPERATURE 65527     // Handle of SYS_TEMPERATURE
#define SYS_TEMPERATURE_idx 4     // Index
#define SYS_PRIORITY 65528        // Handle of SYS_PRIORITY
#define SYS_PRIORITY_idx 5        // Index
#define SYS_COLOR 65529           // Handle of SYS_COLOR
#define SYS_COLOR_idx 6           // Index
#define SYS_LANGUAGE 65530        // Handle of SYS_LANGUAGE
#define SYS_LANGUAGE_idx 7        // Index
#define SYS_OPERATING_TIME 65531  // Handle of SYS_OPERATING_TIME
#define SYS_OPERATING_TIME_idx 8  // Index
#undef USE_OLDSTYLE_VARIABLE_SYMBOLS
#endif

#endif
