/**-----------------------------------------------
 * __gs_PluginNames.c
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with exporting the project
 **-----------------------------------------------*/

const char __gs_ExportedPlugins[] =
  "ATTrueTypeMenuText.\r\n"
  "ATTrueTypeText.\r\n"
  "ATPipeFlow.\r\n";
