/**-----------------------------------------------
 * gdsPrjUserCInfo_CM.c
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with exporting the project
 **-----------------------------------------------*/

#include <gdsPrjUserCInfo.h>

/* ----- Container info ----- */
const tGsContInfo _gs_prjusercinfo_mContInfo[] =
{
    {.mName = "Container0", .mNumber = 0},
    {.mName = "Container1", .mNumber = 1}
};
const size_t _gs_prjusercinfo_mContInfoSize = 2;

/* ----- Mask info ----- */
const tGsMaskInfo _gs_prjusercinfo_mMaskInfo[] =
{
    {.mName = "Maske0", .mNumber = 0}
};
const size_t _gs_prjusercinfo_mMaskInfoSize = 1;

