/**-----------------------------------------------
 * gdsPrjUserCInfo_VR.c
 * This file is automatically generated, don't try to edit it
 * all modifications will be lost with exporting the project
 **-----------------------------------------------*/

#include <gdsPrjUserCInfo.h>

/* ----- Variable info ----- */
const tGsVarInfo _gs_prjusercinfo_mVarInfo[] =
{
    {.mHandle = 1, .mDataType = GS_VAR_DATATYPE_GENERIC, .mName = "STROEMUNG", .mComment = ""},
    {.mHandle = 65524, .mDataType = GS_VAR_DATATYPE_GENERIC, .mName = "SYS_U_SUPPLY", .mComment = ""},
    {.mHandle = 65525, .mDataType = GS_VAR_DATATYPE_GENERIC, .mName = "SYS_ENC_RIGHT", .mComment = ""},
    {.mHandle = 65526, .mDataType = GS_VAR_DATATYPE_GENERIC, .mName = "SYS_ENC_LEFT", .mComment = ""},
    {.mHandle = 65527, .mDataType = GS_VAR_DATATYPE_GENERIC, .mName = "SYS_TEMPERATURE", .mComment = ""},
    {.mHandle = 65528, .mDataType = GS_VAR_DATATYPE_GENERIC, .mName = "SYS_PRIORITY", .mComment = ""},
    {.mHandle = 65529, .mDataType = GS_VAR_DATATYPE_GENERIC, .mName = "SYS_COLOR", .mComment = ""},
    {.mHandle = 65530, .mDataType = GS_VAR_DATATYPE_GENERIC, .mName = "SYS_LANGUAGE", .mComment = ""},
    {.mHandle = 65531, .mDataType = GS_VAR_DATATYPE_GENERIC, .mName = "SYS_OPERATING_TIME", .mComment = ""}
};
const size_t _gs_prjusercinfo_mVarInfoSize = 9;

